### ISSUE TITLE
Something is wrong with link to data

### ISSUE THREAD

**Issue by jilavsky** [bluesky/tiled#372]
Something is wrong with links to data generated by tiled.
I open list of scans in web browser using this search string:
http://usaxscontrol:8000/api/v1/node/search/20idb_usaxs?page[offset]=00&page[limit]=100&filter[time_range][condition][since]=1668816000&filter[time_range][condition][until]=1668902400&filter[time_range][condition][timezone]=US/Central&sort=time

I open random record and I am presented with links - self, search, and full. Self and search links work fine. Link provided to data - e.g.,    http://usaxscontrol:8000/api/v1/node/full/20idb_usaxs/97131bdf-9771-4b21-9916-4db60350466b
returns Internal Server Error
end of tiled log file returns:
```
usaxs@usaxscontrol ~/Documents/tiled $ tail logfile.txt
    return await future
  File "/home/beams11/USAXS/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/beams11/USAXS/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/router.py", line 577, in node_full
    return construct_data_response(
  File "/home/beams11/USAXS/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/core.py", line 298, in construct_data_response
    for spec in [spec.name for spec in specs] + [structure_family]:
  File "/home/beams11/USAXS/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/core.py", line 298, in <listcomp>
    for spec in [spec.name for spec in specs] + [structure_family]:
AttributeError: 'str' object has no attribute 'name'
```
This is link generated by Tiled to my data. This is a 1D scan, it has data. 
I need to download the data as json to Igor Pro. My prior code used following link to get the data : http://usaxscontrol:8000/api/v1/node/full/20idb_usaxs/b4fe8d80-6e4b-473b-b049-086d91f39f99/primary/data?format=json

**Comment by danielballan** [comment]
I think this is the same problem as #371. Quoting myself from there:

> In https://github.com/bluesky/tiled/pull/356, released in tiled v0.1.0a79, we changed spec from a simple string to a dict. We updated databroker in https://github.com/bluesky/databroker/pull/744, released in databroker v2.0.0b12, to align with this change.

> My guess is that you have a too-old version of databroker. Does upgrading fix it?

> Thanks for your patience with the bumps. We made couple backward-incompatible changes over the last month, accounting for what we've learned seeing tiled used in practice.

**Comment by jilavsky** [comment]
@prjemian can you comment on Databroker version? I have no clue what version we are on at this time. And if we can upgrade it without breaking our operations.

**Comment by prjemian** [comment]
tiled server needs a more recent version of databroker (~2.0) than routine data collection (~1.2).  So far, in my testing, I'm getting the same error as @canismarko when trying to view any particular signal that was collected:

```
INFO:     192.168.144.123:50261 - "GET /api/v1/array/full/training/44304716-ed9f-42c5-baa1-dd2179262f11/primary/data/time?format=application/json&slice=0:7 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 567, in set_cookies
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 558, in client_compatibility_check
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 530, in double_submit_cookie_csrf_protection
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 483, in capture_metrics
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/compression.py", line 27, in __call__
    await responder(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/compression.py", line 48, in __call__
    await self.app(scope, receive, self.send_compressed)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/router.py", line 461, in array_full
    return construct_data_response(
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/core.py", line 298, in construct_data_response
    for spec in [spec.name for spec in specs] + [structure_family]:
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/core.py", line 298, in <listcomp>
    for spec in [spec.name for spec in specs] + [structure_family]:
AttributeError: 'str' object has no attribute 'name'
```

**Comment by prjemian** [comment]
Most recently, I tried to construct a _stripped down_ environment where most dependencies are completely managed by pip:

```yml
name: tiled

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.8, <3.11
  - bson
  - pymongo

  - pip:
    - databroker >=2.0.0b12
    - tiled[all] >=0.1.0a80
    - event_model
```

These are the versions of databroker, tiled, and event_model:

```bash
# packages in environment at /home/prjemian/micromamba/envs/tiled:
#
# Name                    Version                   Build  Channel
databroker                2.0.0b12                 pypi_0    pypi
tiled                     0.1.0a80                 pypi_0    pypi
event-model               1.19.0                   pypi_0    pypi
```

**Comment by prjemian** [comment]
This is the server log from the same query (it's a different error but still an error):

```
INFO:     192.168.144.123:50372 - "GET /api/v1/node/search/training/44304716-ed9f-42c5-baa1-dd2179262f11/primary/data/time?page[offset]=0&page[limit]=10&fields= HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 567, in set_cookies
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 558, in client_compatibility_check
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 530, in double_submit_cookie_csrf_protection
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/app.py", line 483, in capture_metrics
    response = await call_next(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 80, in call_next
    raise app_exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/compression.py", line 27, in __call__
    await responder(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/compression.py", line 48, in __call__
    await self.app(scope, receive, self.send_compressed)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/prjemian/micromamba/envs/tiled/lib/python3.10/site-packages/tiled/server/router.py", line 169, in node_search
    raise WrongTypeForRoute(
tiled.server.core.WrongTypeForRoute: This is not a Node; it cannot be searched or listed.
INFO:     192.168.144.123:50373 - "GET /api/v1/array/full/training/44304716-ed9f-42c5-baa1-dd2179262f11/primary/data/time?format=application/json&slice=0:7 HTTP/1.1" 304 Not Modified
```

**Comment by prjemian** [comment]
This was the url in the web browser with tiled's WebUI:  `http://zap:8000/ui/browse/training/44304716-ed9f-42c5-baa1-dd2179262f11/primary/data/time`

**Comment by prjemian** [comment]
BUT, the data is available for download as text from the WebUI

**Comment by prjemian** [comment]
I believe the conda environment setup could be better.  Since this is developing software (both tiled and databroker are not using production versions here), sticking with a mostly-`pip` environment setup seems best for now.  Note that Python must be <3.11, as limited by one of the packages.

The most-recent error above (`tiled.server.core.WrongTypeForRoute: This is not a Node; it cannot be searched or listed.`) is still a nuisance but it does not interrupt the WebUI from rendering a plot of positioner readback v. time, a simple test if tiled is serving data.  Also able to download the data:

```
INFO:     192.168.144.123:50526 - "GET /api/v1/array/full/training/44304716-ed9f-42c5-baa1-dd2179262f11/primary/data/xpos?format=text/html HTTP/1.1" 200 OK
INFO:     192.168.144.123:50527 - "GET /api/v1/array/full/training/44304716-ed9f-42c5-baa1-dd2179262f11/primary/data/xpos?format=text/plain HTTP/1.1" 200 OK
INFO:     192.168.144.123:50528 - "GET /api/v1/array/full/training/44304716-ed9f-42c5-baa1-dd2179262f11/primary/data/xpos?format=application/json HTTP/1.1" 200 OK
```

I'll post the final version of the environment file here next.

**Comment by prjemian** [comment]
Here's the new [`environment.yml`](https://github.com/BCDA-APS/tiled-server/blob/main/environment.yml) file:

```yml
name: tiled

# micromamba create -n tiled -f environment.yml -y
# micromamba activate tiled

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.8, <3.11
  - bson
  - event-model
  - pymongo
  - h5py
  - hdf5plugin
  - punx
  - spec2nexus

  - pip:
    - databroker >=2.0.0b12
    - tiled[all] >=0.1.0a80
    - https://raw.githubusercontent.com/EPICS-synApps/support/master/utils/mdaPythonUtils/mdalib-2022.post9-py2.py3-none-any.whl
```

**Comment by prjemian** [comment]
@jilavsky Does this new environment file solve the problem you reported?

**Comment by prjemian** [comment]
@danielballan - Be amazed that I actually assigned this issue to myself.  What hubris!

**Comment by jilavsky** [comment]
Hurray, and my old Igor code is back in business pulling out my scan data and displaying them. It works again (as it did in May or June)! Good work @prjemian !
This environment took lot longer to build than the prior one.

**Comment by prjemian** [comment]
> This environment took lot longer to build than the prior one.

`pip install` takes longer per package.  But it works.

**Comment by danielballan** [comment]
Ha, I am caught up, and I am duly impressed @prjemian.

I am very glad you are back in business @jilavsky. Enabling integration with things like your Igor work is a large part of why we are building this.
